// resources/js-react/Layouts/DefaultLayout.jsx
import {Link} from "@inertiajs/react";

export default function DefaultLayout({ children }) {
    return <>
        <div>header
            <hr/>
        </div>
        <div>nav
            <Link href="/">Home</Link>
            <Link href="/other">Other</Link>
            <hr/>
        </div>
        <div>
            { children }
            <hr/>
        </div>

        <div>footer
        </div>
    </>
}

// resources/js-vue/Layouts/DefaultLayout.vue
<script setup>
import {Link} from "@inertiajs/vue3";
</script>

<template>
    <div>header<hr></div>
    <div>nav
        <Link href="/">Home</Link>
        <Link href="/other">Other</Link>
        <hr>
    </div>
    <div><slot></slot><hr></div>

    <div>footer<hr></div>

</template>

<style scoped>

</style>
